
[server]
headless = true
port = 10000
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
maxUploadSize = 50

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 10000
